# Generated by Django 2.2.3 on 2019-07-25 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=200)),
                ('tel', models.IntegerField(default=991819934)),
            ],
        ),
        migrations.CreateModel(
            name='ordemservico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(max_length=500)),
                ('servico', models.IntegerField(default=0)),
                ('valor_servico', models.DecimalField(decimal_places=15, max_digits=15)),
                ('valor_produto', models.DecimalField(decimal_places=15, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=15, max_digits=15)),
                ('author', models.IntegerField(default=0)),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='os_servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_servico', models.IntegerField(default=0)),
                ('cod_ordem', models.IntegerField(default=0)),
                ('precoservico', models.DecimalField(decimal_places=15, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
    ]
